export const Users = [
    {
      id:1,
      profilePicture: "../../assets/photo/profile.jpg",
      username: "safak",
    },
    {
      id:2,
      profilePicture: "../../assets/photo/profile2.jpg",
      username: "janell",
    },
    {
      id:3,
      profilePicture: "../../assets/photo/profile3.jpg",
      username: "alexd",
    },
    {
      id:4,
      profilePicture: "../../assets/photo/profile4.jpg",
      username: "DoraHawks",
    },
    {
      id:5,
      profilePicture: "../../assets/photo/profile5.jpg",
      username: "ThomasHolden",
    },
    {
      id:6,
      profilePicture: "../../assets/photo/profile6.jpg",
      username: "Shirley",
    },
    {
      id:7,
      profilePicture: "../../assets/photo/profile7.jpg",
      username: "TravisB",
    },
    {
      id:8,
      profilePicture: "../../assets/photo/profile8.jpg",
      username: "Kristen",
    },
    {
      id:9,
      profilePicture: "../../assets/photo/profile9.jpg",
      username: "Gary",
    },
    {
      id:10,
      profilePicture: "../../assets/photo/profile10.jpg",
      username: "michelle",
    },
  ];
  
  export const Posts = [
    {
      id: 1,
      desc: "Love For All, Hatred For None.",
      photo: "../../assets/photo/1.jpg",
      date: "5 mins ago",
      userId: 1,
      like: 32,
      comment: 9,
    },
    {
      id: 2,
      photo: "../../assets/photo/2.jpg",
      date: "15 mins ago",
      userId: 2,
      like: 2,
      comment: 1,
    },
    {
      id: 3,
      desc: "Every moment is a fresh beginning.",
      photo: "assets/photo/3.jpg",
      date: "1 hour ago",
      userId: 3,
      like: 61,
      comment: 2,
    },
    {
      id: 4,
      photo: "assets/photo/4.jpg",
      date: "4 hours ago",
      userId: 4,
      like: 7,
      comment: 3,
    },
    {
      id: 5,
      photo: "assets/photo/5.jpg",
      date: "5 hours ago",
      userId: 5,
      like: 23,
      comment: 5,
    },
    {
      id: 6,
      photo: "assets/photo/6.jpg",
      date: "1 day ago",
      userId: 6,
      like: 44,
      comment: 6,
    },
    {
      id: 7,
      desc: "Never regret anything that made you smile.",
      photo: "assets/photo/7.jpg",
      date: "2 days ago",
      userId: 7,
      like: 52,
      comment: 3,
    },
    {
      id: 8,
      photo: "assets/photo/8.jpg",
      date: "3 days ago",
      userId: 8,
      like: 15,
      comment: 1,
    },
    {
      id: 9,
      desc: "Change the world by being yourself.",
      photo: "assets/photo/9.jpg",
      date: "5 days ago",
      userId: 9,
      like: 11,
      comment: 2,
    },
    {
      id: 10,
      photo: "assets/photo/10.jpg",
      date: "1 week ago",
      userId: 10,
      like: 104,
      comment: 12,
    },
  ];