version: 2.1
orbs:
  newman: postman/newman@0.0.2
jobs:
  build:
    executor:
      name: newman/postman-newman-docker
      tag: 5.2.0
    steps:
      - checkout
      - newman/newman-run:
          collection: ./CSE4214-Group1-Lab.postman_collection.json
          environment: ./ISE-ENV.postman_environment.json
